version: 0.2

phases:
  pre_build:
    commands:
      - echo "Hello from my pipeline"
      - pip install pipenv
  build:
    commands:
      - echo "Installing dependencies"
      - pip install flask
      - pip install doctest
      - pip install pytest
      - pip install nosetest
      - echo "Testing"
      - python pytest
  post_build:
    commands:
      - echo Build completed on `test-repo`
